export const skills = [
  {
    field: 'Frontend',
    skillsEng: [
      'HTML',
      'CSS',
      'React.js',
      'Tailwind CSS',
      'Javascript',
      'Sass',
      'Next.js',
    ],
    skillsEsp: [
      'HTML',
      'CSS',
      'Typescript',
      'React.js',
      'Tailwind CSS',
      'Javascript',
      'Sass',
      'Next.js',
    ],
  },
  {
    field: 'Backend',
    skillsEng: [
      'Node.js',
      'Express.js',
      'PostgreSQL',
      'MongoDB',
      'Git',
      'Github',
      'NestJS',
      'Docker',
      'TypeORM',
      'Jira',
      'SCRUM agile',
    ],
    skillsEsp: [
      'Node.js',
      'Express.js',
      'PostgreSQL',
      'MongoDB',
      'Git',
      'Github',
      'NestJS',
      'Docker',
      'TypeORM',
    ],
  },
  {
    field: 'Web Design',
    skillsEng: [
      'UX/UI Design',
      'Responsive Design',
      'User Research',
      'Wireframing',
    ],
    skillsEsp: [
      'Diseño UX/UI',
      'Diseño Responsivo',
      'Investigación de Usuarios',
      'Wireframing',
    ],
  },
  {
    field: 'Soft Skills',
    skillsEng: [
      'Collaboration',
      'Effective Communication',
      'Self-sufficient',
      'Proactive',
      'Dedication',
      'SCRUM',
      'Jira',
    ],
    skillsEsp: [
      'Colaboración',
      'Comunicación Efectiva',
      'Autosuficiente',
      'Proactividad',
      'Dedicación',
      'SCRUM',
      'Jira',
    ],
  },
];
